language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
    # make sure git tests do not complain about user/email not being set
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com
    # install dependencies
    - composer install --prefer-dist

script: phpunit --coverage-text