language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env:
        - SYMFONY_VERSION=4.0.*
        - PHPUNIT_VERSION=6.3.*
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;

install: composer update --prefer-dist --no-interaction

before_script:
    # make sure git tests do not complain about user/email not being set
    - git config --global user.name travis-ci
    - git config --global user.email travis@example.com

script: vendor/bin/phpunit --coverage-text
